name: Update Gomodules on Content Change

on:
  repository_dispatch:
    types: [update-gomodules]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_GITHUB }}
    
    - name: Configure Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true
        
    - name: Update go dependencies
      run: |
        go get -u ./...
        go mod tidy
    - name: Create new branch
      run: |
        git checkout -b update-go-modules-branch
    
    - name: Commit changes
      run: |
        git add go.mod
        git commit -m "Update Go dependencies" || echo "No changes to commit"

    - name: Push changes
      run: git push -u origin update-go-modules-branch

    - name: Create Pull Request
      id: create_pr
      run: |
        gh pr create --title "Update Go dependencies" --body "This PR updates the Go module dependencies." --head update-go-modules-branch --base main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

    - name: Enable Auto-Merge
      run: |
        gh pr merge --merge --auto "1" --delete-branch ${{ steps.create_pr.outputs.pull-request-number }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
