name: Update Gomodules on Content Change

on:
  repository_dispatch:
    types: [update-gomodules]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
    - name: Set up Go
      uses: ./
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        
    - name: Update submodule
      run: |
        go get -u
        go mod tidy
