name: Update Gomodules on Content Change

on:
  repository_dispatch:
    types: [update-gomodules]

jobs:
  update-submodule:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable','oldstable']
    
    steps:
    - name: Check out code
    - uses: actions/checkout@v4
    
    - name: Configure Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        
    - name: Update dependencies
      run: |
        go get -u ./...
        go mod tidy
