name: Update Gomodules on Content Change

on:
  repository_dispatch:
    types: [update-gomodules]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true
        
    - name: Update go dependencies
      run: |
        go get -u ./...
        go mod tidy
    
    - name: Commit changes
      run: |
        git add go.mod go.sum
        git commit -m "Update Go dependencies" || echo "No changes to commit"

    - name: Push changes
      run: git push origin main
